import { Provider } from '../types/provider';

export const PRESET_PROVIDERS: Provider[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    defaultApiBase: 'https://api.openai.com/v1',
    supportedModels: [
      {
        id: 'gpt-4-turbo-preview',
        name: 'GPT-4 Turbo',
        provider: 'openai',
        capabilities: { chat: true, imageGeneration: false },
        maxTokens: 128000,
        contextLength: 128000,
        defaultTemperature: 0.7,
      },
      {
        id: 'gpt-4',
        name: 'GPT-4',
        provider: 'openai',
        capabilities: { chat: true, imageGeneration: false },
        maxTokens: 8192,
        contextLength: 8192,
        defaultTemperature: 0.7,
      },
      {
        id: 'gpt-3.5-turbo',
        name: 'GPT-3.5 Turbo',
        provider: 'openai',
        capabilities: { chat: true, imageGeneration: false },
        maxTokens: 4096,
        contextLength: 4096,
        defaultTemperature: 0.7,
      },
      {
        id: 'dall-e-3',
        name: 'DALL-E 3',
        provider: 'openai',
        capabilities: { chat: false, imageGeneration: true },
      },
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    supportedModels: [
      {
        id: 'claude-3-opus',
        name: 'Claude 3 Opus',
        provider: 'anthropic',
        capabilities: { chat: true, imageGeneration: false },
        maxTokens: 32768,
        contextLength: 32768,
        defaultTemperature: 0.7,
      },
      {
        id: 'claude-3-sonnet',
        name: 'Claude 3 Sonnet',
        provider: 'anthropic',
        capabilities: { chat: true, imageGeneration: false },
        maxTokens: 16384,
        contextLength: 16384,
        defaultTemperature: 0.7,
      },
    ],
  },
  {
    id: 'google',
    name: 'Google AI',
    supportedModels: [
      {
        id: 'gemini-pro',
        name: 'Gemini Pro',
        provider: 'google',
        capabilities: { chat: true, imageGeneration: false },
        maxTokens: 32768,
        contextLength: 32768,
        defaultTemperature: 0.7,
      },
      {
        id: 'gemini-pro-vision',
        name: 'Gemini Pro Vision',
        provider: 'google',
        capabilities: { chat: true, imageGeneration: true },
        maxTokens: 32768,
        contextLength: 32768,
        defaultTemperature: 0.7,
      },
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    supportedModels: [
      {
        id: 'mistral-large',
        name: 'Mistral Large',
        provider: 'mistral',
        capabilities: { chat: true, imageGeneration: false },
        maxTokens: 32768,
        contextLength: 32768,
        defaultTemperature: 0.7,
      },
      {
        id: 'mistral-medium',
        name: 'Mistral Medium',
        provider: 'mistral',
        capabilities: { chat: true, imageGeneration: false },
        maxTokens: 32768,
        contextLength: 32768,
        defaultTemperature: 0.7,
      },
      {
        id: 'mistral-small',
        name: 'Mistral Small',
        provider: 'mistral',
        capabilities: { chat: true, imageGeneration: false },
        maxTokens: 32768,
        contextLength: 32768,
        defaultTemperature: 0.7,
      },
    ],
  },
];